# -*- coding: utf-8 -*-

common_spam_words_en = [
    "# 1",
    "$$$",
    "100 %",
    "100 % free",
    "100 % satisfied",
    "4 u",
    "50 % off",
    "accept credit cards",
    "acceptance",
    "access",
    "accordingly",
    "account",
    "act now",
    "action",
    "ad",
    "additional income",
    "addresses on cd",
    "affordable",
    "all natural",
    "all new",
    "amazed",
    "amazing",
    "amazing stuff",
    "apply now",
    "apply online",
    "as seen on",
    "auto email removal",
    "avoid",
    "avoid bankruptcy",
    "avoid bankruptcyaward",
    "awards",
    "bank",
    "bargain",
    "be amazed",
    "be your own boss",
    "being a member",
    "beneficiary",
    "best price",
    "beverage",
    "big bucks",
    "bill 1618",
    "billing",
    "billing address",
    "billion",
    "billion dollars",
    "blood",
    "blow",
    "bonus",
    "boss",
    "brand new pager",
    "bulk email",
    "buy",
    "buy direct",
    "buying judgments",
    "cable converter",
    "call",
    "call free",
    "call now",
    "calling creditors",
    "can fit",
    "can't live without",
    "cancel",
    "cancel at any time",
    "cannot be combined with any other offer",
    "can't live without",
    "cards accepted",
    "cash",
    "cash bonus",
    "cashcashcash",
    "casino",
    "celebrity",
    "cell phone cancer scam",
    "cellulite",
    "cents on the dollar",
    "certified",
    "chance",
    "cheap",
    "check",
    "check or money order",
    "claims",
    "claims not to be selling anything",
    "claims to be in accordance with some spam law",
    "claims to be legal",
    "clearance",
    "click",
    "click below",
    "click here",
    "click to remove",
    "collect",
    "collect child support",
    "compare",
    "compare rates",
    "compete for your business",
    "confidentially on all orders",
    "congratulations",
    "consolidate debt and credit",
    "consolidate your debt",
    "copy accurately",
    "copy dvds",
    "cost",
    "costs",
    "credit",
    "credit bureaus",
    "credit card offers",
    "crystal",
    "crystals",
    "cures",
    "cures baldness",
    "date",
    "deal",
    "deals",
    "dear email",
    "dear fiend",
    "dear friend",
    "dear somebody",
    "death",
    "debt",
    "diabetic",
    "diagnostics",
    "diamond",
    "diamonds",
    "dig up dirt on friends",
    "direct email",
    "direct marketing",
    "discount",
    "do it today",
    "doctor",
    "dollar",
    "dollars",
    "don't delete",
    "don't hesitate",
    "dormant",
    "double your",
    "double your cash",
    "double your income",
    "drastically reduced",
    "earn",
    "earn $",
    "earn extra cash",
    "earn per week",
    "easy terms",
    "eliminate bad credit",
    "eliminate debt",
    "email harvest",
    "email marketing",
    "equipment",
    "eur",
    "euro",
    "exclusive deal",
    "expect to earn",
    "experience",
    "experts",
    "expire",
    "explode your business",
    "extra",
    "extra cash",
    "extra income",
    "f r e e",
    "fantastic",
    "fantastic deal",
    "fast cash",
    "fast viagra delivery",
    "finance",
    "financial",
    "financial freedom",
    "financially independent",
    "fix",
    "for free",
    "for instant access",
    "for just",
    "for just $",
    "for only",
    "for you",
    "form",
    "fortune",
    "free",
    "free access",
    "free cell phone",
    "free consultation",
    "free dvd",
    "free gift",
    "free grant money",
    "free hosting",
    "free info",
    "free installation",
    "free instant",
    "free investment",
    "free leads",
    "free membership",
    "free money",
    "free offer",
    "free preview",
    "free priority mail",
    "free quote",
    "free sample",
    "free trial",
    "free website",
    "freedom",
    "friend",
    "full refund",
    "gains",
    "get",
    "get it now",
    "get out of debt",
    "get paid",
    "get started now",
    "gift certificate",
    "give it away",
    "giving away",
    "gold",
    "great",
    "great offer",
    "grow",
    "growth",
    "guarantee",
    "guaranteed",
    "hardest",
    "have you been turned down",
    "hello",
    "help",
    "here",
    "heritage",
    "hidden",
    "hidden assets",
    "hidden charges",
    "home",
    "home based",
    "home based business",
    "home employment",
    "hormone",
    "hot",
    "huge",
    "human growth hormone",
    "hurry",
    "if only it were that easy",
    "important information regarding",
    "improvement",
    "in accordance with laws",
    "income",
    "income from home",
    "increase sales",
    "increase traffic",
    "increase your sales",
    "incredible deal",
    "info you requested",
    "information you requested",
    "inherit",
    "inheritance",
    "instant",
    "insurance",
    "interest",
    "interested",
    "interesting",
    "internet market",
    "internet marketing",
    "investment",
    "investment decision",
    "it's effective",
    "join millions",
    "join millions of americans",
    "junk",
    "ladies",
    "laser printer",
    "leave",
    "legal",
    "life",
    "life insurance",
    "lifetime",
    "limited",
    "limited time",
    "limited time offer",
    "limited time only",
    "loading",
    "loan",
    "local",
    "long distance phone offer",
    "lose",
    "lose weight",
    "lose weight spam",
    "love",
    "lower interest rates",
    "lower monthly payment",
    "lower your mortgage rate",
    "lowesst",
    "lowest",
    "lowest insurance rates",
    "lowest price",
    "luxury",
    "luxury car",
    "mail in order form",
    "maintained",
    "make $",
    "make money",
    "market",
    "marketing",
    "marketing solutions",
    "mass email",
    "med",
    "medical",
    "medication",
    "medications",
    "medicine",
    "medium",
    "meet singles",
    "member",
    "member stuff",
    "membership",
    "message contains",
    "message contains disclaimer",
    "million",
    "million dollars",
    "millionaire",
    "millionaires",
    "miracle",
    "mlm",
    "money",
    "money back",
    "money making",
    "month trial offer",
    "more internet traffic",
    "mortgage",
    "mortgage rates",
    "multi-level marketing",
    "name brand",
    "need",
    "never",
    "new customers only",
    "new domain extensions",
    "nigerian",
    "no age restrictions",
    "no catch",
    "no claim forms",
    "no cost",
    "no credit check",
    "no disappointment",
    "no experience",
    "no fees",
    "no gimmick",
    "no gimmicks",
    "no hidden",
    "no hidden costs",
    "no interests",
    "no inventory",
    "no investment",
    "no medical exams",
    "no middleman",
    "no obligation",
    "no purchase necessary",
    "no questions asked",
    "no selling",
    "no strings attached",
    "no-obligation",
    "non - stop",
    "non stop",
    "non-stop",
    "nonstop",
    "not intended",
    "not junk",
    "not spam",
    "now",
    "now only",
    "obese",
    "obesity",
    "obligation",
    "offer",
    "offer expires",
    "offshore",
    "once in lifetime",
    "one hundred percent free",
    "one hundred percent guaranteed",
    "one time",
    "one time mailing",
    "one-time",
    "online",
    "online biz opportunity",
    "online degree",
    "online marketing",
    "online pharmacy",
    "only",
    "only $",
    "open",
    "opportunity",
    "opt in",
    "order",
    "order now",
    "order shipped by",
    "order status",
    "order today",
    "orders shipped by priority mail",
    "outstanding values",
    "overnight",
    "passwords",
    "pennies a day",
    "per day",
    "per week",
    "percent",
    "performance",
    "phone",
    "photos",
    "pic",
    "pics",
    "pictures",
    "pill",
    "pills",
    "please read",
    "pleasure",
    "pleasured",
    "potential earnings",
    "pre-approved",
    "prescription",
    "presently",
    "price",
    "print form signature",
    "print out and fax",
    "priority mail",
    "prize",
    "problem",
    "produced and sent out",
    "profits",
    "promise",
    "promise you",
    "purchase",
    "pure profits",
    "quick",
    "quote",
    "rate",
    "rates",
    "real thing",
    "refinance",
    "refinance home",
    "refund",
    "removal",
    "removal instructions",
    "remove",
    "removes wrinkles",
    "request",
    "requires initial investment",
    "reserves the right",
    "reverse",
    "reverses",
    "reverses aging",
    "revolutionary",
    "risk",
    "risk free",
    "risks",
    "rolex",
    "round the world",
    "s 1618",
    "safeguard notice",
    "sale",
    "sales",
    "sample",
    "satisfaction",
    "satisfaction guaranteed",
    "save $",
    "save big money",
    "save up to",
    "score",
    "score with babes",
    "search engine listings",
    "search engines",
    "secret",
    "section 301",
    "see for yourself",
    "sell",
    "selll",
    "sent in compliance",
    "serious",
    "serious cash",
    "serious only",
    "shocking",
    "shopper",
    "shopping spree",
    "sign",
    "sign up free today",
    "signup",
    "social security number",
    "solution",
    "spam",
    "special promotion",
    "stainless steel",
    "stimulate",
    "stimulated",
    "stimulation",
    "stock alert",
    "stock disclaimer statement",
    "stock pick",
    "stop",
    "stop snoring",
    "strong buy",
    "stuff on sale",
    "subject to cash",
    "subject to credit",
    "subscribe",
    "subscriber",
    "subscribers",
    "success",
    "supplies",
    "supplies are limited",
    "supply",
    "take action",
    "take action now",
    "talks about hidden charges",
    "talks about prizes",
    "tells you it's an ad",
    "terms",
    "terms and conditions",
    "the best rates",
    "the following form",
    "they keep your money \xe2\x80\x94 no refund",
    "they're just giving it away",
    "thing",
    "this isn't a scam",
    "this isn't junk",
    "this isn't spam",
    "this won't last",
    "thousands",
    "time limited",
    "today",
    "traffic",
    "trial",
    "undisclosed recipient",
    "university diplomas",
    "unlimited",
    "unsecured credit",
    "unsecured debt",
    "unsolicited",
    "unsubscribe",
    "urgent",
    "us dollars",
    "vacation",
    "vacation offers",
    "view",
    "visit our website",
    "want",
    "wants credit card",
    "warranty",
    "we hate spam",
    "we honor all",
    "web traffic",
    "weekend getaway",
    "weight",
    "weight loss",
    "what are you waiting for",
    "what's keeping you",
    "while supplies last",
    "while you sleep",
    "who really wins",
    "why pay more",
    "wife",
    "will not believe your eyes",
    "win",
    "winner",
    "winning",
    "won",
    "work at home",
    "work from home",
    "wrongfully",
    "you are a winner",
    "you have been selected",
    "your income"
]

common_spam_words_cz = [
    "loterie",
    "lotérie",
    "loterii",
    "lotérii",
    "gratis",
    "sleva",
    "výhra",
    "vyhra",
    "vyhraj",
    "zadarmo",
    "zdarma"
]

forbidden_words = [
    "adult",
    "anal",
    "ass",
    "a@@",
    "blowjob",
    "boobs",
    "boobies",
    "cholesterol",
    "cock",
    "cum",
    "cumshot",
    "deceased",
    "desire",
    "dick",
    "die",
    "died",
    "dildo",
    "erection",
    "fuck",
    "f*ck",
    "hard to buy",
    "hard to believe",
    "hard sex",
    "harder erection",
    "hardest erection",
    "harder erections",
    "hardest erections",
    "heroin",
    "hookup",
    "lesbian",
    "lesbians",
    "lottery",
    "lover",
    "massive",
    "milf",
    "milfs",
    "naughty",
    "nude",
    "nudes",
    "orgasm",
    "orgasms",
    "orgasmic",
    "orgies",
    "orgy",
    "penis",
    "porn",
    "porno",
    "potency",
    "promotional",
    "prozac",
    "pussy",
    "quickie",
    "sexual",
    "sexually",
    "sex",
    "sexy",
    "teen",
    "teens",
    "valium",
    "viagra",
    "vicodin",
    "virgin",
    "virgins",
    "weed",
    "wet",
    "weenie",
    "wiener",
    "xanax"
]
